version: "3.8"
services:
  dev:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run dev
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: development
      DEBUG: True

  prod:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      DEBUG: False