name: Pull Request Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Check test results
      run: |
        if [ ${{ job.status }} == 'failure' ]; then
          exit 1
        fi